version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_lab
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: InfSys
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  minio:
    image: minio/minio:latest
    container_name: minio_lab
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API MinIO
      - "9001:9001"   # Web UI MinIO
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    networks:
      - backend-network

  minio-setup:
    image: minio/mc:latest
    container_name: minio_setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/data;
      "
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  pgdata:
  minio_data: