services:
  db:
    image: postgres:latest
    container_name: postgres_lab
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: InfSys
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio_lab
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # API MinIO
      - "9001:9001"   # Web UI MinIO
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  minio-setup:
    image: minio/mc:latest
    container_name: minio_setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/data;
      "

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      - db

  consumer:
    build: consumer
    deploy:
      replicas: 3
    depends_on:
      - db
      - rabbitmq

#  app: // on release
#    build: .
#    container_name: my-app
#    ports:
#      - "8080:8080"
#    depends_on:
#        - db
#        - rabbitmq

volumes:
  pgdata:
  minio_data:
  rabbitmq_data: