services:
  db:
    image: postgres:latest
    container_name: postgres_lab2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: InfSys
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    depends_on:
      - db

  consumer:
    build: consumer
    deploy:
      replicas: 3
    depends_on:
      - db
      - rabbitmq

#  app: // on release
#    build: .
#    container_name: my-app
#    ports:
#      - "8080:8080"
#    depends_on:
#        - db
#        - rabbitmq

volumes:
    pgdata:
    rabbitmq_data: